# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d03cfd476d0658aea13357c9b591dfca"
name = "live-store-report"
application_url = "https://shopify-live-report.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_reports"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "https://shopify-live-report.onrender.com/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
